### ISSUE TITLE
Add DeSci Summit as Partner with backlinks

### ISSUE THREAD

**Issue by hebbianloop** [desci-eth/SciOS-Home-Site#4]
- Elaborate that the SciOS workshop is a companion event for the DeSci Summit
- Add DeSci Summit as co-host or sponsor
- Add backlinks from SciOS back to DeSci Summit website (will do same on DeSci Summit website)

**Comment by jring-o** [comment]
Done, though without with "co-host" or "sponsor" language

**Comment by hebbianloop** [comment]
wonderful! works great
